import { defineConfig } from 'vite';

export default defineConfig({
  root: './',
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    emptyOutDir: false, // Don't delete the CSS file generated by Tailwind
  },
  server: {
    open: true,
  },
});
